# Sử dụng PHP 8.2 làm base image
FROM php:8.2
# Cài đặt các extension PHP cần thiết
RUN docker-php-ext-install pdo pdo_mysql

# Cài đặt Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# update meta data
RUN apt update

# Cài nano
RUN apt install nano -y

# Thiết lập thư mục làm việc
WORKDIR /var/www/html

# Copy mã nguồn Laravel vào container
#COPY . .

# Cài đặt các dependencies của Laravel bằng Composer
RUN composer install

# Thiết lập quyền truy cập cho storage và cache
RUN chown -R www-data:www-data storage bootstrap/cache
RUN chmod -R 775 storage bootstrap/cache

# Expose cổng 80
EXPOSE 80

# Khởi động web server PHP
CMD ["php", "artisan", "serve", "--host", "0.0.0.0", "--port", "80"]
