version: '3.8'

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile.new
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html/app
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
    networks:
      - app-network

  mysql:
    image: mysql:8.2
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginxnew/:/etc/nginx/conf.d/
      - ./:/var/www/html/app
    depends_on:
      - laravel
    networks:
      - app-network

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
